server:
  port: 8080

spring:
  application:
    name: idms

  datasource:
    url: jdbc:mysql://localhost:3306/idms?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 8595629739

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  jackson:
    serialization:
      write-dates-as-timestamps: false

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

idms:
  security:
    basic:
      username: admin
      password: admin

